### ISSUE TITLE
能否更新一下支持Laravel 5.0

### ISSUE THREAD

**Issue by JellyBool** [hardywen/social-login#1]
这个目前在Laravel 5.0使用好像在安装的时候会有不少坑，能不能更新一下更好的支持laravel 5.0？

**Comment by hardywen** [comment]
抱歉，这个组件的目的就是为了方便自己在公司的项目中使用而已。而公司现在还不考虑使用laravel5，所以这个组件暂时不会升级。而且关键是我也没看过5.0。
不过我可以考虑一下分支一个5.0版本出来，但时间上不能保证。

**Comment by JellyBool** [comment]
OK,了解
