### ISSUE TITLE
 "code" and "state" params

### ISSUE THREAD

**Issue by fanly** [hardywen/social-login#2]
您好，获取 "code" and "state" params之后，怎么使用呢？不懂~~望指导

**Comment by hardywen** [comment]
登录之后，页面会跳转到你配置里面的 callback url， 在这个 calback url （回调页面） 调用 SocialLogin::consumer('QQ')->callBack();
之后用
SocialLogin::consumer('QQ')->getUserInfo(); 获取用户数据

**Comment by fanly** [comment]
嗯 好 谢谢您，还有一个问题：getUserInfo()，sina返回的是数组，qq返回的是object，json_encode方法稍微有点小问题，没统一
public function getUserInfo() {

```
    $graph_url = "https://graph.qq.com/user/get_user_info"
            . "?access_token=" . $this->accessToken
            . "&oauth_consumer_key=" . $this->appid
            . "&openid=" . $this->uid;

    $str = file_get_contents($graph_url);

    $user = json_decode($str, true);

    return $user;
}
```

**Comment by hardywen** [comment]
好的，我统一一下。
